config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  # get '/log',     to: 'home#log'
  # post '/log',    to: 'home#log'

  resources :games, only: [:new, :create]
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :played_on, presence: true, allow_nil: false, allow_blank: false
  has_many :game_scores
  has_many :users, through: :game_scores
end

app/models/game_form.rb
class GameForm
  include ActiveModel::Model

  attr_reader :owner

  def self.build(owner, attrs = {})
    service = new(owner, attrs)
    service
  end

  def initialize(owner, attrs)
    @owner = owner
    @attrs = attrs
  end

  def opponents_list
    User.where.not(id: owner.id)
  end

  def save(game_params = {})
    @game_params = game_params
    persist_records
  end

  private

  def persist_records
    begin
      ActiveRecord::Base.transaction do
        game = Game.create!(game_attrs)
        owner_score = GameScore.create!(owner_attrs.merge(game: game))
        opponent_score = GameScore.create!(opponent_attrs.merge(game: game))
      end
      true
    rescue => e
      errors.add(:game, e.message)
      return false
    end
  end

  def game_attrs
    game_params.fetch(:game, {})
  end

  def opponent_attrs
    game_params.fetch(:opponent, {})
  end

  def owner_attrs
    {
      user_id: owner.id,
      score: game_params.fetch(:score, 0)
    }
  end

  attr_reader :attrs, :game_params
end

app/models/game_history.rb
class GameHistory
  attr_reader :records

  def self.build(user)
    service = new(user)
    service.run
    service
  end

  def initialize(user)
    @user = user
  end

  def run
    @records = build_games
  end

  private

  attr_reader :user, :game_scores

  def get_scores
    @game_scores = user.scores.includes(:game)
  end

  def build_games
    user.games.map do |game|
      GamePresenter.new(game, user)
    end
  end
end

app/models/game_score.rb
class GameScore < ActiveRecord::Base
  belongs_to :game
  belongs_to :user

  validates :score, :game_id, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :scores, class_name: "GameScore"
  has_many :games, through: :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @form = GameForm.build(current_user)
  end

  def create
    @form = GameForm.build(current_user)
    if @form.save(game_params)
      redirect_to history_path, notice: "Game successfully added"
    else
      flash[:error] = @form.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def game_params
    params.require(:game_form).permit(
      :score,
      game: [:played_on],
      opponent: [:score, :user_id],
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def history
    @game_history = GameHistory.build(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="col-sm-12">
  <%= form_tag games_path, method: :post, class: "form form-horizontal" do %>
    <div class="form-group">
      <%= label_tag "Date played", nil, class: "control-label col-sm-3" %>
      <div class="col-sm-9">
        <%= date_select "game_form[game]", "played_on", {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "Opponent", nil, class: "control-label col-sm-3" %>
      <div class="col-sm-9">
        <%= select_tag "game_form[opponent][user_id]", options_from_collection_for_select(@form.opponents_list, :id, :email), class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "Your Score", nil, class: "control-label col-sm-3" %>
      <div class="col-sm-9">
        <%= number_field_tag "game_form[score]", 0, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag "Their Score", nil, class: "control-label col-sm-3" %>
      <div class="col-sm-9">
        <%= number_field_tag "game_form[opponent][score]", 0, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-9 col-sm-prefix-3">
        <%= submit_tag "Save", class: "btn btn-primary" %>
        <%= link_to "Cancel", root_path, class: "btn btn-link" %>
      </div>
    </div>
  <% end %>
</div>
<div class="clearfix"></div>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="games-history">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Date</th>
        <th>Opponent</th>
        <th>Score</th>
        <th>Result</th>
      </tr>
    </thead>
    <tbody>
      <% @game_history.records.each do |game| %>
        <tr>
          <td><%= game.date %></td>
          <td><%= game.opponent.email %></td>
          <td><%= game.score %></td>
          <td><%= game.result %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<div class="alert alert-warning" role="alert">This is a sample page.</div>

<%= image_tag('leaderboard.png') %>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<div class="col-sm-12">
  <%= form_tag log_path, method: :post, class: "form form-horizontal" do %>
    <div class="form-group">
      <%= label_tag "Date played", nil, class: "control-label col-sm-3" %>
      <div class="col-sm-9">
        <%= date_select "game_form[game][played_on]" %>
      </div>
    </div>
  <% end %>
</div>
<div class="clearfix"></div>

<%= image_tag('log_game.png') %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', new_game_path, class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <% if flash.any? %>
      <% flash.each do |type, message| %>
        <p class="alert alert-warning"><%= message %></p>
    <% end %>

    <% end %>
    <%= yield %>
  </div>
</body>
</html>